import { LoaderCircle, Sparkles, X } from "lucide-react";
import type { BriefingCacheEntry } from "./notesWorkspaceShared";

export interface NotesAiPanelProps {
  briefing: BriefingCacheEntry;
  /** Whether a to-do with this exact text already exists on the ticket. */
  hasTodoText: (text: string) => boolean;
  onAddTodo: (text: string) => void;
  onClose: () => void;
}

/** AI briefing panel: grounded risk/question suggestions with one-click to-do capture. */
export const NotesAiPanel = ({ briefing, hasTodoText, onAddTodo, onClose }: NotesAiPanelProps) => (
  <section className="notes-panel notes-ai-panel" aria-label="AI briefing">
    <header>
      <Sparkles size={14} />
      <strong>AI briefing</strong>
      <span className="notes-panel-meta">{briefing.sourceLabel}</span>
      <button type="button" className="notes-panel-close" onClick={onClose} aria-label="Close AI briefing">
        <X size={13} />
      </button>
    </header>
    {briefing.status === "loading" ? (
      <div className="notes-panel-loading">
        <LoaderCircle className="notes-spinner" size={14} />
        Reading ticket description, comments, and pull request…
      </div>
    ) : briefing.suggestions.length ? (
      <div className="notes-ai-suggestions">
        {briefing.suggestions.map((suggestion) => {
          const added = hasTodoText(suggestion.text);
          return (
            <div className="notes-ai-suggestion" key={suggestion.id}>
              <span className={`is-${suggestion.kind}`}>{suggestion.kind}</span>
              <p>{suggestion.text}</p>
              <button
                type="button"
                className={added ? "is-added" : ""}
                disabled={added}
                onClick={() => onAddTodo(suggestion.text)}
              >
                {added ? "Added ✓" : "+ to-do"}
              </button>
            </div>
          );
        })}
      </div>
    ) : (
      <p className="notes-panel-empty">No grounded suggestions were returned. Your notes are unchanged.</p>
    )}
    <footer>
      Suggestions, not facts — generated by your AI provider from ticket data. Your notes stay local and are never
      sent.
    </footer>
  </section>
);
